spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=smartCityInfo
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true

#CLOUDINARY_URL=${CLOUDINARY_URL}
CLOUD_NAME=${CLOUD_NAME}
API_KEY=${API_KEY}
API_SECRET=${API_SECRET}
JWT_SECRET_KEY=${JWT_SECRET_KEY}